### ISSUE TITLE
Avoid .coffee extension in import statements?

### ISSUE THREAD

**Issue by tad-lispy** [lautis/rollup-plugin-coffee-script#3]
Hello and thanks for this plugin.

I'm just starting with Rollup and wonder if this is a right place for this issue, or should I file it under the main Rollup repo. Anyway this is more of a question than issue.

I'd like to import a module without specifying it's extensions, like that:

```coffee
import { add } from "./math"
```

provided that there is a `math.coffee` file in the same directory. It gives me a following error:

```
Could not resolve './math' from /**/src/index.coffee
```

It works if I provide an extension in my `import` statement:

```coffee
import { add } from "./math.coffee"
```

but I would like to avoid specifying extensions, so that my code is more portable. How should I do that?

With Browserify I can provide `--extensions` option and it would resolve the module correctly. Is there an equivalent for Rollup? I've found that rollup/rollup-plugin-node-resolve allows to specify extensions - is this a way to go?

**Comment by lautis** [comment]
It's possible to avoid using the extensions with [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve). I've added that to the example in readme.
